[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "88f29d6e8a6f50a29fc58551fb9023efb2c7b5ba"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "6330878a517bc2cd24fdb89066d1f91b20de66484d6149e3750a07d2a30158cf"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.1.4+0/XGBoost.v2.1.4.i686-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "afa624511d952cca6a638cadca9692ea7581e8ae"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "c60ee506f0992e68ba793201b0f7f440a6721eb2ffc91267ee6c46ccb37b3eb5"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.1.4+0/XGBoost.v2.1.4.i686-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "47d79d28fad98e7210bc90b407d17aa7dc5905a2"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "9143357d02ad076af5c383a88878925840f106bc96508cd78f89945885617d7c"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.1.4+0/XGBoost.v2.1.4.x86_64-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b5cd6ca75255f04f2f82e5c21f8fdc81b1b439a3"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "9ab9e48667e5e84583e9d09d8d4fa007f85ebf50543651abcd79886664d4b4c9"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.1.4+0/XGBoost.v2.1.4.x86_64-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "139c09c31a129a49aadf72201e96a16f80dce477"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "bbcfd483c9b0775046aa94b3f472f7e1ab03a51e622c4949c7df6b93f279cf37"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.1.4+0/XGBoost.v2.1.4.aarch64-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d3d0bc0e1b6053806774ce857d04851af4d82cdd"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "ea37accfbbde4f43273fc6c04f241e2a192bd49119fd896852c1d9db814465b7"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.1.4+0/XGBoost.v2.1.4.aarch64-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e1fc1430256b8547f725c47f557f9cf0a2650aa3"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "37b218e985a5b04dc18fa19983444ff4322fbafe7b04def2e09c272f16b851ee"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.1.4+0/XGBoost.v2.1.4.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "573289b8a37d8bb20d2cc99dda06dac2e015c311"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "72e0819871ed62f92a82b528daed386e8511402409e8295878047e7c6717b721"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.1.4+0/XGBoost.v2.1.4.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "343707d9fe216bfebdc98f375b39f643c1002da1"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "474f32f7f02c168a5331f5cc94b5cd31101b754cd678ef637834288b738514cc"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.1.4+0/XGBoost.v2.1.4.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aae213fbfdf8ca5d89a094e1863f5edde29b7185"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "837276251aaf1b80f201f8a72412c5facb5b916bb7b121f79d95fde803b2ad97"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.1.4+0/XGBoost.v2.1.4.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "35bc0f5fe1cbcde457bca2f276581c4c088d5db7"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "69cff91717dced38300786d8c7fe6bf1a6444d65704cbc35984b336790b9f6de"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.1.4+0/XGBoost.v2.1.4.powerpc64le-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7e27afd0d56fb528cc4c1a0a5e36a1aaf5c5d69d"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "775111fbddb104ce15f6de2bd7203ff320bb3dcebcb83bb367e53bb020bc13c9"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.1.4+0/XGBoost.v2.1.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0cd0186804e52548ac360c38b9be555b4153d625"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "b6ddeb9f06d39ead90446dfb65cc4af8895c25da3f5a25c20a7e5a889dd284fb"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.1.4+0/XGBoost.v2.1.4.riscv64-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a99d11937912ad8b41b50e189f5f069a35a59552"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "1a939f81f36a2340ed6f4ef659d9e06423174132033055d3558091a50acc3f3f"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.1.4+0/XGBoost.v2.1.4.riscv64-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cb397f739eb0b4aecb964d6420f25e1fdb9f5ccf"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "d72bb236fe7d55eea7fb552398155aec1baadff850a6b9990697d980d94965b4"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.1.4+0/XGBoost.v2.1.4.i686-linux-musl-cxx03.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e47b77bddc1b80fd5106b94378f478740c0d3332"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "5f7615273e482b25f6ace3f478756e0055e514f5cdfca580805924b171e482d1"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.1.4+0/XGBoost.v2.1.4.i686-linux-musl-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d2decfaa7a833c93e06c87aac36aea953a94695e"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "d2a4f82da01766ceff786aa0419dae01e09de92b9451fe0198d290dd4067369a"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.1.4+0/XGBoost.v2.1.4.x86_64-linux-musl-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "36c21d3dd722e935394af838901450964da3358c"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "bfe75c25d1011a055f2a6a1f418ff621f5d524599660cfef8e2bd77fc8478efc"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.1.4+0/XGBoost.v2.1.4.x86_64-linux-musl-cxx11.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dba7dd8844b3d553d2fa4a7a78b99d1e1f242ccb"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "58f5ea155e2e697e8a8213bfe16b40152f9fee7d9c4af684d515c836ff27ad6f"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.1.4+0/XGBoost.v2.1.4.aarch64-linux-musl-cxx03.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "76d13b88dcf6186168c8cc91a94b7058c5660937"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "b02adc8f8447c55b5ad01f5809de16306f39a5b52acd6d76689732fa1c07dfa9"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.1.4+0/XGBoost.v2.1.4.aarch64-linux-musl-cxx11.tar.gz"
[[XGBoost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f0bcc8bebf88b0b02aa13281c470228c8c94051b"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "4eb707c28bc49046d0d6257a67cf762654931d2d9517a8de9c3502db6121b75f"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.1.4+0/XGBoost.v2.1.4.armv6l-linux-musleabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b781c48bc65fa6cb233bcf06467c70280daafda"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "777e680d27afaafe8fc99aa7eaee800283290d67b61832ba31b6a34c6f0b6a90"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.1.4+0/XGBoost.v2.1.4.armv6l-linux-musleabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5440ac6742a774c5ccf3f2bb432d8e9ac081c907"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "0a8e3069f01d7ac81c7dd8a56cf1fc81b0a290efa40289d6cb111960cd431d24"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.1.4+0/XGBoost.v2.1.4.armv7l-linux-musleabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "782ec541b9f7f07f0c87f725beed36eed4061032"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "5bebe474b485c5a8f86c27b14570ae420727004e436a9e361b6030b7025412d1"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.1.4+0/XGBoost.v2.1.4.armv7l-linux-musleabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
git-tree-sha1 = "b9dd5f0106845ece6565d536edd87ce429c4b3b8"
os = "macos"

    [[XGBoost.download]]
    sha256 = "12d9f97efe138b55213bfeb18cc1ae3ae7841aeae04f7e69d38573c361bc5b1f"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.1.4+0/XGBoost.v2.1.4.x86_64-apple-darwin.tar.gz"
[[XGBoost]]
arch = "aarch64"
git-tree-sha1 = "49d46b9620852adf1a4661d6e7eb94199689a9d2"
os = "macos"

    [[XGBoost.download]]
    sha256 = "7cb9351aa0ec2c1f0d6a44ab4deae23cd443e0b664e6bd518e66a8578100faae"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.1.4+0/XGBoost.v2.1.4.aarch64-apple-darwin.tar.gz"
[[XGBoost]]
arch = "x86_64"
git-tree-sha1 = "a7d09fb393236107954b69dfa6438ea9a4eb00f0"
os = "freebsd"

    [[XGBoost.download]]
    sha256 = "5b44e6fbd114cef4286350784f5c1a0fed707358fbeafbc995e4718e5917ec68"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.1.4+0/XGBoost.v2.1.4.x86_64-unknown-freebsd.tar.gz"
[[XGBoost]]
arch = "aarch64"
git-tree-sha1 = "4aef213ec631e40840886973bb19b734edcdb354"
os = "freebsd"

    [[XGBoost.download]]
    sha256 = "9cd4dccfaac69c69ea17369eb059ad91cbcb1359a0f030d88d147d5c27c6c893"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.1.4+0/XGBoost.v2.1.4.aarch64-unknown-freebsd.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1ca88ed3bb041f6dd2f2417f97711af45c4a5635"
os = "windows"

    [[XGBoost.download]]
    sha256 = "fa59a7be71cab6bf022d0a13ac0f8d3c35425d26855a920a90ff117c1e896d2e"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.1.4+0/XGBoost.v2.1.4.i686-w64-mingw32-cxx03.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3bd3b2c5eaf202dbe7e45baea861629632b30a58"
os = "windows"

    [[XGBoost.download]]
    sha256 = "2f54eb755e31df7047ec6810da7c174df9a3189d11fb09df219fbe7318019179"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.1.4+0/XGBoost.v2.1.4.i686-w64-mingw32-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "07b31cc0101c6d37cf0da1c558e9f8771080e252"
os = "windows"

    [[XGBoost.download]]
    sha256 = "63c174fcd089f6e352cb3f7b3ac20c90471c8568c563436730fba1a2e85517da"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.1.4+0/XGBoost.v2.1.4.x86_64-w64-mingw32-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f3de5dcb42896c3813ce81fa7ce91d23b29f8220"
os = "windows"

    [[XGBoost.download]]
    sha256 = "1d47618ed853f701d0dbdf8e6c300e22c9f0cc4d0313707cfc62fc3f5f98b043"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.1.4+0/XGBoost.v2.1.4.x86_64-w64-mingw32-cxx11.tar.gz"
